var Activity = {
	ZERO: 0,
	INICIO: 4,
	ANALISE_RESPONSAVEL_PROJETO: 10,
	ANALISE_RESPONSAVEL_OBJETIVO_ESTRATEGICO: 13,
	ANALISE_PLANEJAMENTO_ESTRATEGICO: 17,
	ANALISE_DIRETOR_ADJUNTO: 22,
	ANALISE_DIRETORA_EXECUTIVA: 26,
	AJUSTES: 34,
	FIM_NAO_APROVADO_ADJUNTO: 42,
	FIM_NAO_APROVADO: 32,
	FIM_APROVADO: 30,
	APROVADO: 28,
	GERAR_FORM_VERTSIGN: 54
};